export const REQUEST_PRODUCT_LIST_TO_SPRING = 'REQUEST_PRODUCT_LIST_TO_SPRING'
export const REQUEST_PRODUCT_TO_SPRING = 'REQUEST_PRODUCT_TO_SPRING'
export const REQUEST_PURCHASE_LIST_TO_SPRING = 'REQUEST_PURCHASE_LIST_TO_SPRING'
export const REQUEST_PURCHASE_TO_SPRING ='REQUEST_PURCHASE_TO_SPRING'
export const REQUEST_MY_PURCHASE_LIST_TO_SPRING= 'REQUEST_MY_PURCHASE_LIST_TO_SPRING'


