export const MANAGEMENT_QUESTION_BOARD_LIST = 'MANAGEMENT_QUESTION_BOARD_LIST'
export const MANAGEMENT_QUESTION_BOARD = 'MANAGEMENT_QUESTION_BOARD'
export const MANAGEMENT_ANSWER_BOARD = 'MANAGEMENT_ANSWER_BOARD'