export const REQUEST_CARD_LIST_TO_SPRING = 'REQUEST_CARD_LIST_TO_SPRING'
export const REQUEST_ACCOUNT_LIST_TO_SPRING = 'REQUEST_ACCOUNT_LIST_TO_SPRING'
export const REQUEST_USER_INFO_TO_SPRING = 'REQUEST_USER_INFO_TO_SPRING'
export const REQUEST_CARD_INFO_TO_SPRING = 'REQUEST_CARD_INFO_TO_SPRING'