export const MANAGEMENT_BOARD = 'MANAGEMENT_BOARD'
export const MANAGEMENT_BOARD_LIST = 'MANAGEMENT_BOARD_LIST'
export const MYPAGE_BOARD = 'MYPAGE_BOARD'
export const MANAGEMENT_QUESTION_BOARD_LIST = 'MANAGEMENT_QUESTION_BOARD_LIST'